language: ruby
before_install: rm Gemfile.lock || true
script:
  - "bundle exec rake spec"
matrix:
  include:
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 3.3.0"
    gemfile: .gemfile
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.3.0"
    gemfile: .gemfile
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.7.3"
    gemfile: .gemfile
  - rvm: 2.1.1
    env: PUPPET_VERSION="~> 3.7.3"
    gemfile: .gemfile
notifications:
  email:
    - al@lab42.it
